name: replace_vars_dev

on:
    workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Replace vaiable values 
      run: |
        touch ./dags/config/test.json
        sed '/s/rndc-airflow-poc/${{ vars.S3_BUCKET_DATA }}/g' ./dags/config/config.json > ./dags/config/test.json
        
    - name: View config file
      run: |
        cat ./dags/config/config.json > ./dags/config/test.json
        git config --global user.email "bharath9t7@gmail.com"
        git config --global user.name "Bharath9t7"
        git status
        git add .
        git commit -a -m "replace values in json file"
        git push
