name: replace_vars_prod

on:
    workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Replace variable values 
      run: |

        sed -i 's|s3://s3-github-airflow-dev|${{vars.S3_BUCKET_DATA}}|' ./dags/config/config.json
        sed -i 's|db_raw_dev|${{vars.DB_NAME}}|' ./dags/config/config.json 
    
    - name: Commit changes
      run: |
        git config --global user.email "bharath9t7@gmail.com"
        git config --global user.name "Bharath9t7"
        git status
        git add .
        git commit -a -m "replace values in json file"
        git push