name: replace_vars_dev

on:
    workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Replace vaiable values 
      run: |
        sed -i '/s/rndc-airflow-poc/${{vars.S3_BUCKET_DATA}}/g' 
            ./dags/config/config.json
    
    - name: View config file
      run: |
        cat ./dags/config/config.json
