name: replace_vars_dev

on:
    workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Replace vaiable values 
      run: |
        sed -e '/s/rndc-airflow-poc/${{vars.S3_BUCKET_DATA}}/g' \
            -e '/s/db_raw_poc/${{vars.DB_NAME}}/g' \
            ./dags/config/config.json > ./dags/config/config.json
        cat ./dags/config/config.json
