name: aws-s3-sync-dev

on:
  workflow_run:
    workflows: [CI Test Dev]
    types: [completed]
    branches:
      - dev
      
env:
  GITHUB_REF: "refs/heads/dev"

jobs:
  deploy:
    name: s3-sync-dev
    
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: dev
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
        
    - name: Sync changes to s3
      run: aws s3 sync ./dags ${{vars.DEV_S3_BUCKET}} --delete
